swagger: '2.0'
info:
    title: semantic-search-testing Testing API
    description: Sample API on API Gateway with a Google Cloud Functions backend
    version: 1.0.0
schemes:
    - https
produces:
    - application/json
security:
    -   firebase: [ ]
securityDefinitions:
    firebase:
        authorizationUrl: ""
        flow: "implicit"
        type: "oauth2"
        x-google-issuer: "https://securetoken.google.com/speedy-atom-413006"
        x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
        x-google-audiences: "speedy-atom-413006"
paths:
    /ingest_file:
        post:
            summary: Uploads to Cloud Storage
            description: Securely uploads a file to cloud storage and records the upload metadata in a Firestore database.
            operationId: ingestFile
            x-google-backend:
                address: https://us-central1-speedy-atom-413006.cloudfunctions.net/ingest_file
                disable_auth: True # the cloud function will handle authorization
                deadline: 3600.0 # timeout for one hour for testing
            parameters:
                -   name: Authorization
                    in: header
                    description: Bearer token for ID authentication
                    required: true
                    type: string
                -   name: file
                    in: formData
                    description: The file to upload
                    required: true
                    type: string
                    # type: file is not allowed
                    # See https://cloud.google.com/endpoints/docs/openapi/openapi-limitations#file_upload
            responses:
                '200':
                    description: The file has been successfully uploaded.
                    schema:
                        type: object
                        properties:
                            objectId:
                                type: string
                                description: Unique object ID for the uploaded file.
                            timestamp:
                                type: string
                                description: Timestamp of the upload.
                            status:
                                type: string
                                description: Upload status.
                '401':
                    description: Unauthorized. No Authorization header provided or the ID token is missing.
                '403':
                    description: Forbidden. The ID token is invalid or expired.
                '405':
                    description: Method Not Allowed. HTTP method other than POST was used.
